# Generated by Django 2.0.6 on 2018-06-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_comment_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
